### ISSUE TITLE
GNOME runtime report page shows minimal ISO report

### ISSUE THREAD

**Issue by oliviacrain** [NixOS/reproducible.nixos.org#4]
Commit f3f614a replaced the contents of the `nixos-iso-gnome-runtime` page with a report for the minimal ISO.

I'm running some reproducibility experiments on my aarch64 machine, and it'd be nice to have some data to compare my results to!

**Comment by raboof** [comment]
Oops! Sorry about that, I just updated it again - https://reproducible.nixos.org/nixos-iso-gnome-runtime/ - you might need to 'refresh'
